### ISSUE TITLE
Chandas: Include गुरु-लगु-विन्यास (द दा द दा दा द द दा द दा दा etc) as headword

### ISSUE THREAD

**Issue by suhasm** [indic-dict/stardict-sanskrit-kAvya#11]
Every entry already has "मात्रा-विन्यास" of the form द दा द दा दा. It should be included as headword to allow tune --> name lookup.

**Comment by vvasuki** [comment]
कृतम् - अर्धवादनात् परं कोशसञ्चिका सिद्धा स्यात्।

**Comment by suhasm** [comment]
धन्योस्मि
