### ISSUE TITLE
rk-maTh encyclopedia - lists not scraped

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit-kAvya#5]
@damooo kindly scraped rk-maTh encyclopedia - https://github.com/indic-dict/stardict-sanskrit/issues/110#issuecomment-550143895 . Very useful. 

However, it is missing some lists:

For example: compare http://eoh.rkmathbangalore.org/describe/word/ekav%C4%81kyat%C4%81 with:

```
एकवाक्यता

ekavākyatā
(‘single sentence-ness’)
------------------------------------------

While interpreting the various passages from the वेदस् and the उपनिषद्स्, the ancient and medieval commentators have exercised great care. One of the principles they have adopted in their commentaries and interpretations is ‘ekavākyatā’.

A vākya or a sentence is not just an aggregate of words, grammatically or syntactically connected. It should also convey sense. When the sense is not complete and needs further clarification, which is given in one or two or more sentences, all these sentences together will then have ‘ekavākyatā.’

For instance, take these sentences:

There are three sentences here. Each one of them conveys a different idea. But all the three put together produce a single knowledge in our मिन्द्, viz., that there is fire on the hill. Thus there is एकवाक्यता in all these three statements.
```

@damooo - will you take this up?

**Comment by damooo** [comment]
Now, it should support every element.

updated script and babylon file are in following folder
https://drive.google.com/open?id=1upfvlrtWYl2lndrUX-jg0Mw7lbm_yjaH

**Comment by damooo** [comment]
A note that,
headwords are not strictly iast xliterated sanskrit, but some are direct english (ignorance, mind, etc.), some are mix (vedas, upanishads). Thus we cannot distinguish to xliterate only sanskrit words. It may not be problem in headwords. But in description, it currently xliterates headwords to devanagari at hyperlinks, for readablity. It may be wrong thing to do, as above descr shows ( मिन्द् for mind).

We can keep them as they are if required. (or can have both).
