### ISSUE TITLE
Create Catalogus catalogorum dict

### ISSUE THREAD

**Issue by vvasuki** [indic-dict/stardict-sanskrit-kAvya#8]
- Digitized here - https://vmlt.in/library?page=1#
- Also DLI - https://vmlt.in/library?page=1#

**Comment by gasyoun** [comment]
You are aware of the .rar archive of it, right? 
Lately it's been updated, error correction @vvasuki

**Comment by vvasuki** [comment]
Thanks for the rar archive. Created source files at https://github.com/indic-dict/stardict-sanskrit-kAvya/tree/master/ncc . The dictionary is available at https://github.com/indic-dict/stardict-sanskrit-kAvya/raw/gh-pages/tars/ncc__2021-03-02_08-18-07Z__10MB.tar.gz
